# host                  handler (executed via /bin/sh -c)
mylocal.hello           /usr/local/bin/handlers/hello.sh
mylocal.shim            /usr/local/bin/handlers/shim_meta.py
mylocal.kafka           /usr/local/bin/handlers/kafka.py
mylocal.redis           /usr/local/bin/handlers/redis_kv.py
mylocal.mongo           /usr/local/bin/handlers/mongo.py
mylocal.postgres        /usr/local/bin/handlers/postgres.py
mylocal.rabbit          /usr/local/bin/handlers/rabbit.py
mylocal.smtp            /usr/local/bin/handlers/smtp.py
mylocal.grpc            /usr/local/bin/handlers/grpc_reflect.py
